# yaml-language-server: $schema=content-config_scheme.json

general:
  displayName: "Allgemeines"
  items:
    - fileTitle: "Vorstandberichte der letzten 3 Jahre"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.5"
      helpText: "Vorstandbericht.md"
    - fileTitle: "Alle Mitgliederzufriedenheitsanalysen im Prüfungszeitraum"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.6"
      helpText: "Mitgliederzufriedenheitsanalyse.md"

processes:
  displayName: "Prozesse"
  items:
    - fileTitle: "Modellierungshandbuch"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.1.3"
      helpText: "Prozessmanagement.md"
    - fileTitle: "Schulungsprozess"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.2"
      helpText: "Schulungsprozess.md"
    - fileTitle: "Dokumentation des Prozessveränderungsverlaufs"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.1.3"
      helpText: "Schulungsprozess.md"
    - fileTitle: "KV- Dokumentation über den Prüfungszeitraum"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.7"
      helpText: "Kontinuierliche Verbesserung.md"
    - fileTitle: "Mitgliederaufnahmeprozess"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.3.1"
      helpText: "Mitgliederaufnahmeprozess.md"
    - fileTitle: "Dokumentation des Prozessveränderungsverlaufs"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.1.3"
      helpText: "Mitgliederaufnahmeprozess.md"
    - fileTitle: "Projektbesetzungsprozess"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.4.1.1"
      helpText: "Projektbesetzungsprozess.md"
    - fileTitle: "Dokumentation des Prozessveränderungsverlaufs"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.1.3"
      helpText: "Projektbesetzungsprozess.md"
    - fileTitle: "Projektcontrolling-Prozess"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.4.1.2"
      helpText: "Projektcontrolling-Prozess.md"
    - fileTitle: "Dokumentation des Prozessveränderungsverlaufs"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.1.3"
      helpText: "Projektcontrolling-Prozess.md"
    - fileTitle: "Kundenevaluationsprozess"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.4.1.3"
      helpText: "Kundenevaluationsprozess.md"
    - fileTitle: "Dokumentation des Prozessveränderungsverlaufs"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.1.3"
      helpText: "Kundenevaluationsprozess.md"
    - fileTitle: "Projektdokumentationsprozess"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.4.1.4"
      helpText: "Projektdokumentationsprozess.md"
    - fileTitle: "Dokumentation des Prozessveränderungsverlaufs"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.1.3"
      helpText: "Projektdokumentationsprozess.md"

projects:
  displayName: "Projekte"
  items:
    - fileTitle: "Projektdokumentationen"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.4.2"
      helpText: "Realisierung der Projekte.md"
    - fileTitle: "Abschlusspräsentationen"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.4.2"
      helpText: "Realisierung der Projekte.md"
    - fileTitle: "Hochladen der optionalen Dokumente"
      allowedFormats: ".pdf"
      legalRef: "GO QM §2.1.3"
      helpText: "Angabe zur Einsendung optionaler Dokumente.md"

trainings:
  displayName: "Schulungen"
  items:
    - fileTitle: "Pflichtschulungen"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.3.2"
      helpText: "BDSU-Schulungen.md"
    - fileTitle: "Zusätzliche Pflichtschulungen"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.2.4"
      helpText: "BDSU-Schulungen.md"

members:
  displayName: "Mitglieder"
  items:
    - fileTitle: "Teilnahme an den Pflichtschulungen des zu prüfenden Mitglieds"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.3.2.2"
      helpText: "Realisierung der Mitgliederaufnahme.md"
    - fileTitle: "Nachweis von mindestens 3 BT in einem AWP Projekt des zu prüfenden Mitglieds"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.3.2.2"
      helpText: "Realisierung der Mitgliederaufnahme.md"
    - fileTitle: "Erstelltes Angebot des zu prüfenden Mitglieds"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.3.2.2"
      helpText: "Realisierung der Mitgliederaufnahme.md"
    - fileTitle: "Abschlusspräsentation des zu prüfenden Mitglieds"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.3.2.2"
      helpText: "Realisierung der Mitgliederaufnahme.md"
    - fileTitle: "zusätzlichen vereinsspezifischen Mitgliedsanforderungen"
      allowedFormats: ".pdf"
      legalRef: "GO QM §3.3.2.2"
      helpText: "Realisierung der Mitgliederaufnahme.md"
